### ISSUE TITLE
Error when cchardet fails to return an encoding

### ISSUE THREAD

**Issue by metaisfacil** [doujincafe/hbcl#7]
Using the latest HBCL pip installed from this repo. On occasion cchardet is unable(?) to detect a specific file encoding, in which case `cchardet.detect()` will return a dict with the encoding and confidence key values both set to None. HBCL currently assumes the confidence value will always be a type/object supporting comparison, and when it isn't a TypeError is thrown.

Example affected log file: [BUCK-TICK - TABOO.log](https://github.com/doujincafe/hbcl/files/9892350/BUCK-TICK.-.TABOO.log)
Example script for reproduction:
```
from heybrochecklog import score_log
from pathlib import Path
import os


log_file = os.path.join(os.getcwd(), "BUCK-TICK - TABOO.log")
log_report = score_log(Path(log_file))
print(log_report)

```

Output:
```
Traceback (most recent call last):
  File "...\test.py", line 7, in <module>
    log_report = score_log(Path(log_file))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\heybrochecklog\score\__init__.py", line 14, in score_log
    contents = get_log_contents(log_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\heybrochecklog\shared.py", line 12, in get_log_contents
    encoding = get_log_encoding(log_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\heybrochecklog\shared.py", line 26, in get_log_encoding
    return result['encoding'] if result['confidence'] > 0.7 else 'utf-8-sig'
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

One simple workaround to hide the problem is adjusting the comparison on line 26 of shared.py like so:
```
        return result['encoding'] if (result['confidence'] or 0) > 0.7 else 'utf-8-sig'
```

This is obviously a copout but a more robust solution is beyond my current abilities.

**Comment by fumiichan** [comment]
Yeah, it turns out cchardet doesn't support 'MacRoman'. So yeah, will revert the change of using cchardet to chardet instead.

**Comment by fumiichan** [comment]
As it turns out, one cannot support the other encoding out there. Someone should standardise the log character encoding to remove this type of headache in detecting character encoding.

Neither of these packages (cchardet or chardet) is a bullet-proof solution and may require both of them to be there.

Both packages can output different character encoding on the same log file and one of them could either break and throw an exception or detect and produce bad result.

Will see what I can do.
